---
title: "on-sam"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{on-sam}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = FALSE,
  warning = FALSE,
  comment = "#>"
)
```

```{r}
library(fishvice)
library(dplyr)
library(ggplot2)
```


```{r}
fit <- sam_get_fit("NEA_cod_AFWG_2021")
rbya <- sam_rbya(fit, data = TRUE)
rby  <- sam_rby(fit)
opr <- sam_opr(fit, lgs = FALSE, scale = 1e6)
```

```{r, fig.width=7}
rbya %>% 
  mutate(yc = year - age) %>% 
  ggplot(aes(year, oC, fill = factor(yc))) +
  theme_bw() +
  geom_col() +
  facet_grid(age ~ ., scales = "free_y") +
  scale_fill_crayola() +
  theme(legend.position = "false") +
  scale_y_continuous(NULL, NULL) +
  labs(x = NULL, y = NULL,
       title = "Catch in numbers by age and yearclass")
```

```{r, fig.width = 7}
rby %>% 
  ggplot() + 
  theme_bw() +
  geom_ribbon(aes(year, ymin = low, ymax = high),
              fill = "grey") +
  geom_line(aes(year, est)) +
  facet_wrap(~ variable, scales = "free_y") +
  expand_limits(y = 0) +
  labs(x = NULL, y = NULL,
       tile = "Stock summary")
```

```{r}
opr$plots$`Residual catch`
opr$plots$IBWSS
```

```{r}
pro <- sam_process_error(rbya, plot_it = TRUE, plot_catch = TRUE)
pro$mort
pro$abun
pro$mass
```

